ci(browserstack): moved to custom retry
It seems that nick-invision/retry@v2 hides our output till it completes, plus we don't
want the wait for browser stack availability to trigger the retry timeout, but we need it
within the retry, so trying to roll custom retry logic, with a timeout only on the test run.
This also allows use to only create the tunnel when needed.

diff --git a/.github/workflows/build-and-publish.yml b/.github/workflows/build-and-publish.yml
--- a/.github/workflows/build-and-publish.yml
+++ b/.github/workflows/build-and-publish.yml
@@ -346,31 +346,94 @@ jobs:
         with:
           username: ${{ secrets.BROWSERSTACK_USERNAME }}
           access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
+
+      # browserstack can be moody at times, so let
+      # the pipeline have a few cracks at it
+
+      ### FIRST ATTEMPT ###
+      # wait for availability
       - run: npm run wait-for-browser-stack
         env:
           BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
           BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
+      # create tunnel
       - uses: "browserstack/github-actions/setup-local@v1.0.1"
         with:
           local-testing: start
           local-identifier: random
-
-      # browserstack can be moody at times, so let
-      # the pipeline have a few cracks at it
-      - uses: nick-invision/retry@v2
-        with:
-          timeout_seconds: 1500
-          max_attempts: 3
-          retry_wait_seconds: 10
-          command: npm run wait-for-browser-stack && npm run cover:browser-api:${{ matrix.browser }}:remote
-        env:
-          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
-          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
-          MAX_INIT_WAIT_TIME: 60
-
+      # run tests
+      - id: attempt-1
+        run: |
+          npm run cover:browser-api:${{ matrix.browser }}:remote \
+          && echo "::set-output name=result::sucesss\n" || 
+          && echo "::set-output name=result::failed\n"
+        timeout-minutes: 25
+        continue-on-error: true
+      # stop tunnel
       - uses: "browserstack/github-actions/setup-local@v1.0.1"
         with:
           local-testing: stop
+
+      ### SECOND ATTEMPT ###
+      # wait for availability
+      - run: npm run wait-for-browser-stack
+        if: steps.attempt-1.outputs.result == 'failed'
+        env:
+          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
+          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
+      # create tunnel
+      - uses: "browserstack/github-actions/setup-local@v1.0.1"
+        if: steps.attempt-1.outputs.result == 'failed'
+        with:
+          local-testing: start
+          local-identifier: random
+      # run tests
+      - id: attempt-2
+        if: steps.attempt-1.outputs.result == 'failed'
+        run: |
+          npm run cover:browser-api:${{ matrix.browser }}:remote \
+          && echo "::set-output name=result::success\n" || 
+          && echo "::set-output name=result::failed\n"
+        timeout-minutes: 25
+        continue-on-error: true
+      # stop tunnel
+      - uses: "browserstack/github-actions/setup-local@v1.0.1"
+        if: steps.attempt-1.outputs.result == 'failed'
+        with:
+          local-testing: stop
+
+      ### THRID ATTEMPT ###
+      # wait for availability
+      - run: npm run wait-for-browser-stack
+        if: steps.attempt-1.outputs.result == 'failed' && steps.attempt-2.outputs.result == 'failed'
+        env:
+          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
+          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
+      # create tunnel
+      - uses: "browserstack/github-actions/setup-local@v1.0.1"
+        if: steps.attempt-1.outputs.result == 'failed' && steps.attempt-2.outputs.result == 'failed'
+        with:
+          local-testing: start
+          local-identifier: random
+      # run tests
+      - id: attempt-3
+        if: steps.attempt-1.outputs.result == 'failed' && steps.attempt-2.outputs.result == 'failed'
+        run: |
+          npm run cover:browser-api:${{ matrix.browser }}:remote \
+          && echo "::set-output name=result::success\n" || 
+          && echo "::set-output name=result::failed\n"
+        timeout-minutes: 25
+        continue-on-error: true
+      # stop tunnel
+      - uses: "browserstack/github-actions/setup-local@v1.0.1"
+        if: steps.attempt-1.outputs.result == 'failed' && steps.attempt-2.outputs.result == 'failed'
+        with:
+          local-testing: stop
+
+      # fail if the third attempt failed
+      - run: exit 1
+        if: steps.attempt-1.outputs.result == 'failed' && steps.attempt-2.outputs.result == 'failed' && steps.attempt-3.outputs.result == 'failed'
+
       - uses: actions/upload-artifact@v2
         with:
           name: code-coverage-report-${{ matrix.browser }}
